version: '3.9'

networks:
    localdev:
        name: localdev

services:
    db-sql:
        image: mcr.microsoft.com/mssql/server:2022-latest
        container_name: db-sql
        environment:
            ACCEPT_EULA: "Y"
            SA_PASSWORD: ${SA_PASSWORD}
        ports:
            - "1433:1433"
        networks:
            - localdev
    api:
        build: ./src/
        environment:
            - "ASPNETCORE_ENVIRONMENT=Development"
            - "ConnectionStrings:DefaultConnection=${CONNECTION_STRING?err}"
            - "Authentication:JwtOptions:Key=${JWT_KEY?err}"
            - "Authentication:JwtOptions:Issuer=http://localhost:5000/"
            - "Authentication:JwtOptions:Audience=http://localhost:5000/"
        restart: always
        ports:
            - "5000:80"
            - "5001:443"
        depends_on:
            - db-sql
        networks:
            - localdev
                    