services:
  api:
    environment:
      - "ASPNETCORE_ENVIRONMENT=Development"
      - "ConnectionStrings:DefaultConnection=Server=db-sql;Database=GoCodeDbDev;User=sa;Password=${SA_PASSWORD};TrustServerCertificate=True;"
      - "Authentication:JwtOptions:Issuer=http://localhost:5000/"
      - "Authentication:JwtOptions:Audience=http://localhost:5000/"
    ports:
      - "5000:80"
