version: '3.9'

networks:
    localdev:
        name: localdev

services:
    db-sql:
        image: mcr.microsoft.com/mssql/server:2022-latest
        container_name: db-sql
        environment:
            ACCEPT_EULA: "Y"
            SA_PASSWORD: ${SA_PASSWORD?err}
        user: root
        ports:
            - "1433:1433"
        networks:
            - localdev
        volumes:
            - db-data:/var/opt/mssql/data
        
    api:
        build: ./src/
        environment:
            - "ASPNETCORE_ENVIRONMENT=Development"
            - "ConnectionStrings:DefaultConnection=${CONNECTION_STRING?err}"
            - "Authentication:JwtOptions:Key=${JWT_KEY?err}"
            - "Admin:Email=${ADMIN_EMAIL?err}"
            - "Admin:Username=${ADMIN_USERNAME?err}"
            - "Admin:Password=${ADMIN_PASSWORD?err}"
        restart: always
        depends_on:
            - db-sql
        networks:
            - localdev
volumes:
    db-data:
