version: '3.9'

services:
    api:
        environment:
            - "ASPNETCORE_ENVIRONMENT=Development"
            - "Authentication:JwtOptions:Issuer=http://localhost:5000/"
            - "Authentication:JwtOptions:Audience=http://localhost:5000/"
        ports:
            - "5000:80"
