version: '3.9'

networks:
    localdev:
        name: localdev

services:
    db-sql:
        image: mcr.microsoft.com/mssql/server:2022-latest
        container_name: db-sql
        environment:
            ACCEPT_EULA: "Y"
            SA_PASSWORD: "Your_password123"
        ports:
            - "1433:1433"
        networks:
            - localdev
    api:
        build: .
        environment:
            - "ASPNETCORE_ENVIRONMENT=Development"
            - "ConnectionStrings:DefaultConnection=Server=db-sql;Database=GoCodeTestDb;User=sa;Password=Your_password123;"
            - "Authentication:JwtOptions:Key=super_secret_key"
            - "Authentication:JwtOptions:Issuer=http://localhost:5000/"
            - "Authentication:JwtOptions:Audience=http://localhost:5000/"
        restart: always
        ports:
            - "5000:80"
            - "5001:443"
        depends_on:
            - db-sql
        networks:
            - localdev
                    