name: CD

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  dotnet-build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v2.1.0
        with:
          dotnet-version: 7.0.x

      - name: Restore dependencies
        run: dotnet restore ./src/api/GoCode.sln

      - name: Build
        run: dotnet build ./src/api/GoCode.sln --configuration Release --no-restore

      - name: Publish
        run: dotnet publish ./src/api/GoCode.WebAPI/GoCode.WebAPI.csproj -c Rlease -o ${{ env.DOTNET_ROOT }}/api

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: api-artifact-test
          path: ${{env.DOTNET_ROOT}}/api

  deploy-test:
    runs-on: ubuntu-latest
    needs: dotnet-build-and-publish
    environment:
      name: "Test"
      url: ${{ steps.deploy-to-azure.outputs.webapp-url }}
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: api-artifact-test

      - name: Deploy to Azure Web App
        id: deploy-to-azure
        uses: azure/webapps-deploy@v2
        with:
          app-name: gocodeapi-test
          publish-profile: ${{ secrets.PUBLISH_PROFILE_TEST }}
