name: CI

# Controls when the workflow will run
on:
    # Triggers the workflow on push or pull request events
    push:
        branches: [ main, develop, release/* ]
    pull_request:
        branches: [ main, develop, release/* ]
    workflow_dispatch:

env:
  API_IMAGE: gocode:api

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  dotnet-build-and-test:
  # The type of runner that the job will run on
      runs-on: ubuntu-latest
      steps:
        - name: Checkout repository
          uses: actions/checkout@v3
        - name: Setup .NET
          uses: actions/setup-dotnet@v2.1.0
          with:
            dotnet-version: 6.0.x
        - name: Restore dependencies
          run: dotnet restore ./src/api/GoCode.sln
        - name: Build
          run: dotnet build ./src/api/GoCode.sln --configuration Release --no-restore
        - name: Run unit tests
          run: dotnet test ./tests/GoCode.UnitTests/GoCode.UnitTests.csproj --verbosity normal
  docker-build-and-push:
      runs-on: ubuntu-latest
      needs: dotnet-build-and-test
      steps:
        - name: Checkout repository
          uses: actions/checkout@v3
        - name: Login to DockerHub
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
            name: Build and push
        - name: Build and push API image
          uses: docker/build-push-action@v3
          with:
              context: ./src/api/
              file: ./src/api/Dockerfile
              builder: ${{ steps.buildx.outputs.name }}
              push: true
              tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.API_IMAGE }}
 
