name: CI

# Controls when the workflow will run
on:
    # Triggers the workflow on push or pull request events
    push:
        branches: [ main, develop ]
    pull_request:
        branches: [ main, develop ]

    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  dotnet-build-and-test:
  # The type of runner that the job will run on
      runs-on: ubuntu-latest
      steps:
        - name: Checkout repository
          uses: actions/checkout@v3
        - name: Setup .NET
          uses: actions/setup-dotnet@v2.1.0
          with:
            dotnet-version: 6.0.x
        - name: Restore dependencies
          run: dotnet restore ./src/api/GoCode.sln
        - name: Build
          run: dotnet build ./src/api/GoCode.sln --configuration Release --no-restore
        - name: Run unit tests
          run: dotnet test ./tests/GoCode.UnitTests/GoCode.UnitTests.csproj --verbosity normal
