# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - gocodeapi

on:
  push:
    branches:
      - feature/15-CDPipeline
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_20def9506deb4de5aee3621336ae71f1 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_a245b758a60e4a6287b54ec6695fba8c }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_20def9506deb4de5aee3621336ae71f1 }}/wiktoriakeller/gocode:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'gocodeapi'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_77ea27c148554aab91dd9d338153b710 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_20def9506deb4de5aee3621336ae71f1 }}/wiktoriakeller/gocode:${{ github.sha }}'